env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:react/recommended
  - airbnb
  - plugin:react/jsx-runtime
  - airbnb-typescript
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:react-hooks/recommended
  - plugin:prettier/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
  - '@typescript-eslint'
  - import
  - prettier
rules:
  react/jsx-fragments:
    - 1
    - element
  react/jsx-props-no-spreading: off
  react/prop-types: off
  react/require-default-props: off
  prettier/prettier:
    - 1
    - {}
    - usePrettierrc: true
  import/no-extraneous-dependencies:
    - 2
    - devDependencies: true
  import/prefer-default-export: 0
  camelcase: off
  '@typescript-eslint/naming-convention': 0
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
      - .tsx
  import/resolver:
    typescript:
      alwaysTryTypes: true
