semi: false
tabWidth: 2
useTabs: false
printWidth: 100
singleQuote: true
trailingComma: es5
bracketSpacing: true
proseWrap: preserve
parser: typescript
overrides:
  - files: src/**/*.css
    options:
      singleQuote: false
      parser: postcss
